/**:
  ros__parameters:
    # General Parameters
    vehicle_name: 'opencav'
    controller_mode: 'simulator'
    loop_trajectory: False
    use_external_target_vel: True
    external_target_vel: 0.5
    lateral_deviation: 0.0
    # Longitudinal Controller Parameters
    kp_longitudinal: 0.2
    acceleration_limit: 0.16
    # Lateral Controller Parameters
    wheel_base: 3.09
    lookahead_time: 3.0
    min_lookahead: 3.0
    kp_lateral: 1.16
    kd_lateral: 6.9
    steer_limit: 1.0