/**:
  ros__parameters:
    # General Parameters
    vehicle_name: 'hunter'
    controller_mode: 'simulator'
    loop_trajectory: False
    use_external_target_vel: True
    external_target_vel: 1.0
    lateral_deviation: 0.0
    # Longitudinal Controller Parameters
    kp_longitudinal: 0.2
    acceleration_limit: 0.3
    # Lateral Controller Parameters
    wheel_base: 0.55
    lookahead_time: 3.0
    min_lookahead: 3.0
    kp_lateral: 6.9
    kd_lateral: 16.0
    steer_limit: 1.0